apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: us-central1-docker.pkg.dev/swift-implement-405417/repo/react-app:20250403-1217
          ports:
            - containerPort: 80