name: Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  REPOSITORY: repo
  IMAGE_NAME: react-app
  GKE_CLUSTER: gke-cluster

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install Google Cloud SDK and gke-gcloud-auth-plugin
        run: |
          sudo apt-get update
          sudo apt-get install -y curl apt-transport-https ca-certificates gnupg
          
          # Add the correct Google Cloud public key
          curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
          
          # Add Google Cloud SDK repo
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list
          
          # Update and install required package
          sudo apt-get update
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

      - name: Set up kubectl
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER --region $REGION --project $PROJECT_ID

      - name: Deploy to GKE
        run: |
          kubectl apply -f manifestsfiles/deployment.yml
          kubectl apply -f manifestsfiles/service.yml
